// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Smiley.Data;

#nullable disable

namespace Aflevering2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230130230909_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Smiley.Data.Models.Company", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("companyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cvr")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Smiley.Data.Models.Report", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("companyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("smileyFace")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("companyId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Smiley.Data.Models.Report", b =>
                {
                    b.HasOne("Smiley.Data.Models.Company", null)
                        .WithMany("companyReports")
                        .HasForeignKey("companyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Smiley.Data.Models.Company", b =>
                {
                    b.Navigation("companyReports");
                });
#pragma warning restore 612, 618
        }
    }
}
